(12.1)  запрет на закрытие окна создания по esc + фильтрация фото
htmlacademy-univer-javascript-1/2166951-kekstagram-4 pull request #12
Opened 2023-12-16 10:19 UTC by AYDLIOH04

добавил запрет на закрытие окна с созданием картинки, если открыто окно с ошибкой загрузки + фильтрация

2023-12-16 12:49 UTC, MaksimovG requested changes

2023-12-16 12:49 UTC, MaksimovG commented on js/filters.js
> +};
а если попап закрыт, зачем нам живущие в нем обработчики? А вот такие `ilters.addEventListener('click', (evt) => {` анониманые обработчики снять нельзя к тому же.

2023-12-16 12:49 UTC, MaksimovG commented on js/messages.js
>    exitButton.removeEventListener('click', hideMessage);
Критерий по обработчикам

2023-12-16 12:49 UTC, MaksimovG commented on js/filters.js
> +const filters = document.querySelector('.img-filters');
filtersContainer, читая filters - множественное число - ожидаешь внутри коллекцию элементов, а не один элемент

2023-12-17 09:40 UTC, MaksimovG requested changes

2023-12-17 09:40 UTC, MaksimovG commented on js/messages.js
>    exitButton.removeEventListener('click', hideMessage);
Проигнорирован

2023-12-17 09:40 UTC, MaksimovG commented on js/messages.js
>    exitButton.removeEventListener('click', hideMessage);
его, кстати,можно не снимать, если весь блок удаляется через remove, то все обработчики, которые были внутри него слетают автоматически, но критерий названия все равно нарушен.

2023-12-17 09:42 UTC, AYDLIOH04 commented on js/messages.js
>    exitButton.removeEventListener('click', hideMessage);
В смысле? Яж изменил обработчик

2023-12-17 09:49 UTC, AYDLIOH04 commented on js/messages.js
>    exitButton.removeEventListener('click', hideMessage);
Этот обработчик импортируемый из другого файла чтоб отслеживать состояние ошибки и запрешать закрытие по ESC попапа  с созданием картинки, когда попап с ошибкой открыт. Это сторонний обработчик и то по идеи просто функция, так как его я ни на что не навешиваю

2023-12-17 09:53 UTC, MaksimovG commented on js/messages.js
>    exitButton.removeEventListener('click', hideMessage);
мы не эспортируем обработчики из других модулей

2023-12-17 09:54 UTC, MaksimovG commented on js/messages.js
>    exitButton.removeEventListener('click', hideMessage);
Из модулей экспортируются только управляющие модулем функции. С сохранением принципа инкапсуляции

2023-12-17 09:54 UTC, MaksimovG commented on js/messages.js
>    exitButton.removeEventListener('click', hideMessage);
Попапы в модулях могут стать разными и перестать использовать один блок в разметке.

2023-12-17 09:58 UTC, AYDLIOH04 commented on js/messages.js
>    exitButton.removeEventListener('click', hideMessage);
Согласен, исправлю.

2023-12-17 10:41 UTC, merged